name: Resumator

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      LINKEDIN_API_KEY: ${{ secrets.LINKEDIN_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        token: ${{ secrets.PUSH_TOKEN }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24' 
        cache: true

    - name: Run program with verbose logging
      run: |
        set -x
        go run main.go || { echo "Go program execution failed"; exit 1; }
      shell: bash

    - name: Cache Docker image
      id: cache
      uses: actions/cache@v3
      with:
        path: /tmp/.docker-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Pull Docker image with logging
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        set -x
        docker pull danteev/texlive || { echo "Failed to pull Docker image"; exit 1; }
        mkdir -p /tmp/.docker-cache
        docker save danteev/texlive | gzip > /tmp/.docker-cache/texlive.tar.gz
      shell: bash

    - name: Load Docker image from cache with logging
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        set -x
        gunzip -c /tmp/.docker-cache/texlive.tar.gz | docker load || { echo "Failed to load Docker image from cache"; exit 1; }
      shell: bash

    - name: Run pdflatex in Docker with debug output
      run: |
        set -x
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace danteev/texlive pdflatex resume.tex || { echo "pdflatex execution failed"; cat resume.log || echo "No log file found"; exit 1; }
      shell: bash

    - name: Commit and Push Changes with logging
      run: |
        set -x
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m '[AUTO]: Updated resume' || echo "No changes to commit"
        git push || { echo "Git push failed"; exit 1; }
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
      shell: bash

    - name: Upload Artifacts with logging
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: |
          resume.pdf
          resume.tex
        if-no-files-found: error
        retention-days: 5
