name: Resumator

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-latest
    timeout-minutes: 3 
    env:
      LINKEDIN_API_KEY: ${{ secrets.LINKEDIN_API_KEY }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        token: ${{ secrets.TOKEN }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24' 
        cache: true

    - name: Run program
      run: go run main.go

    - name: Cache TinyTeX
      uses: actions/cache@v3
      with:
        path: ~/.TinyTeX
        key: ${{ runner.os }}-tinytex-2024

    - name: Install TinyTeX
      run: |
        if [ ! -d "$HOME/.TinyTeX" ]; then
          curl -fsSL "https://yihui.org/tinytex/install-bin-unix.sh" | sh
        fi
        export PATH="$HOME/.TinyTeX/bin/x86_64-linux:$PATH"
        tlmgr install enumitem hyperref xcolor biblatex ragged2e parskip
        pdflatex -interaction=nonstopmode -halt-on-error resume.tex
        
    - name: Cache TeX packages
      uses: actions/cache@v3
      with:
        path: ~/.texlive/texmf-var
        key: ${{ runner.os }}-tex-${{ hashFiles('resume.tex') }}

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        # Configure token-based push
        git remote set-url origin https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/${{ github.repository }}

        git add .
        git commit -m '[AUTO]: Updated resume' || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: |
          resume.pdf
          resume.tex
        if-no-files-found: error
        retention-days: 5
