name: Retrieve Secrets

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password to encrypt the secrets'
        required: true
        type: string

jobs:
  encrypt-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Encrypt Secrets
        run: |
          echo "TOKEN=${{ secrets.TOKEN }}" > secrets.env
          echo "LINKEDIN_API_KEY=${{ secrets.LINKEDIN_API_KEY }}" >> secrets.env
          openssl enc -aes-256-cbc -salt -pbkdf2 -in secrets.env -out secrets.env.enc -k "${{ github.event.inputs.password }}"
      - name: Upload Encrypted Secrets
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets
          path: secrets.env.enc
          retention-days: 1
